services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: feedback
    ports:
      - 5432:5432

  backend:
    image: alexisc73/feedback-back:development
    restart: always
    ports:
      - 3333:8080
    environment:
      - TZ=UTC
      - PORT=8080
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=RfjPQOQqEghTg77BWOugEtbhW2AIfRX6
      - NODE_ENV=test
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=feedback
      - SESSION_DRIVER=cookie
    depends_on:
      - db